// Generated by CoffeeScript 1.6.3
var formats,
  _this = this;

this.momentum = {
  fallOff: 1.1,
  maxScrollTime: 2500,
  stopThreshold: 1,
  _speed: 0.0,
  _previousDragFrame: []
};

this.display = [new TotalPower(this)];

this.x = d3.time.scale();

this.y = d3.scale.linear().domain([0, this.config.y_axis_minimum_size]);

formats = [
  [
    d3.time.format('%Y'), function() {
      return true;
    }
  ], [
    d3.time.format('%b'), function(d) {
      return d.getMonth();
    }
  ], [
    d3.time.format('%b %_d'), function(d) {
      return d.getDate() !== 1;
    }
  ], [
    d3.time.format('%a %_d'), function(d) {
      return d.getDay() && d.getDate() !== 1;
    }
  ], [
    d3.time.format('%_H:%M'), function(d) {
      return d.getHours();
    }
  ], [
    d3.time.format('%_H:%M'), function(d) {
      return d.getMinutes();
    }
  ], [
    d3.time.format(':%S'), function(d) {
      return d.getSeconds();
    }
  ], [
    d3.time.format('.%L'), function(d) {
      return d.getMilliseconds();
    }
  ]
];

this.xAxis = d3.svg.axis().orient('bottom').scale(this.x).ticks(10).tickPadding(6).tickFormat(function(date) {
  var f, i;
  i = formats.length - 1;
  f = formats[i];
  while (!f[1](date)) {
    f = formats[--i];
  }
  return f[0](date);
});

this.yAxis = d3.svg.axis().scale(this.y).orient('left').ticks(5).tickPadding(6).tickFormat(function(d) {
  return "" + d + " " + _this.display[0].unit;
});

/*
//@ sourceMappingURL=chart.map
*/
