// Generated by CoffeeScript 1.6.3
window.ES || (window.ES = {
  Graph: {},
  Data: {},
  Config: {},
  Bubbles: {}
});

ES.Graph.Viewport = (function() {
  function Viewport() {
    this.inited = true;
  }

  return Viewport;

})();
